import { createFileRoute } from "@tanstack/react-router";
import { DataPage } from "@/components/admin/DataPage";
import { StatusBadge } from "@/components/admin/AdminUI";
import { supabase } from "@/lib/admin/list";
import { adminHead, fmt, text, type AnyRow } from "@/lib/admin/head";

export const Route = createFileRoute("/_authenticated/admin/papers")({
  head: adminHead("Practice Papers", "Papers generated by students."),
  component: () => (
    <DataPage<AnyRow>
      title="Practice Papers"
      subtitle="Papers generated by students."
      heading="Generated papers"
      description="Live feed of practice paper generation."
      queryKey={["papers"]}
      build={() => supabase.from("practice_papers").select("*").order("created_at", { ascending: false }).limit(300) as never}
      empty="No papers generated yet."
      columns={[
        { label: "Title", render: (r) => text(r["title"]) },
        { label: "Subject", render: (r) => text(r["subject"]) },
        { label: "Status", render: (r) => <StatusBadge value={String(r["status"] ?? "")} /> },
        { label: "Created", render: (r) => fmt(r["created_at"]) },
      ]}
    />
  ),
});
