// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eqablwzpdrxoiryjfang.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVxYWJsd3pwZHJ4b2lyeWpmYW5nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODU4MTEyMjAsImV4cCI6MjEwMTM4NzIyMH0.FtUoTl1XhL9P0AsTwv1rdQKzEtEwmQCWF1x84kB0hDY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});